"""create movie tables

Revision ID: a201684c5a16
Revises: df50edb535df
Create Date: 2026-04-17 11:45:09.245332

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a201684c5a16'
down_revision: str | Sequence[str] | None = 'df50edb535df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'category',
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('slug', sa.String(length=128), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_category')),
        sa.UniqueConstraint('name', name=op.f('uq_category_name')),
        sa.UniqueConstraint('slug', name=op.f('uq_category_slug')),
    )
    op.create_table(
        'movie',
        sa.Column('title_original', sa.String(length=512), nullable=True),
        sa.Column('title_ru', sa.String(length=512), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('year', sa.SmallInteger(), nullable=True),
        sa.Column('duration_minutes', sa.SmallInteger(), nullable=True),
        sa.Column('age_rating', sa.String(length=16), nullable=True),
        sa.Column('imdb_rating', sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column('kinopoisk_rating', sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column('tmdb_rating', sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column('country', sa.String(length=128), nullable=True),
        sa.Column('poster_url', sa.String(length=1024), nullable=True),
        sa.Column('trailer_url', sa.String(length=1024), nullable=True),
        sa.Column('imdb_id', sa.String(length=16), nullable=True),
        sa.Column('kp_id', sa.String(length=16), nullable=True),
        sa.Column('tmdb_id', sa.String(length=16), nullable=True),
        sa.Column('media_type', sa.Enum('FILM', 'SERIES', name='mediatype'), nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.CheckConstraint(
            'title_original IS NOT NULL OR title_ru IS NOT NULL',
            name=op.f('ck_movie_title_required'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_movie')),
        sa.UniqueConstraint('imdb_id', name=op.f('uq_movie_imdb_id')),
        sa.UniqueConstraint('kp_id', name=op.f('uq_movie_kp_id')),
        sa.UniqueConstraint('tmdb_id', name=op.f('uq_movie_tmdb_id')),
    )
    op.create_table(
        'person',
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('original_name', sa.String(length=256), nullable=True),
        sa.Column('photo_url', sa.String(length=1024), nullable=True),
        sa.Column('birth_date', sa.Date(), nullable=True),
        sa.Column('country', sa.String(length=128), nullable=True),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_person')),
    )
    op.create_table(
        'movie_category',
        sa.Column('movie_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['category_id'],
            ['category.id'],
            name=op.f('fk_movie_category_category_id_category'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['movie_id'],
            ['movie.id'],
            name=op.f('fk_movie_category_movie_id_movie'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('movie_id', 'category_id', name=op.f('pk_movie_category')),
    )
    op.create_table(
        'movie_person',
        sa.Column('movie_id', sa.Integer(), nullable=False),
        sa.Column('person_id', sa.Integer(), nullable=False),
        sa.Column(
            'role_type', sa.Enum('ACTOR', 'DIRECTOR', 'WRITER', name='roletype'), nullable=False
        ),
        sa.Column('character_name', sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ['movie_id'],
            ['movie.id'],
            name=op.f('fk_movie_person_movie_id_movie'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['person_id'],
            ['person.id'],
            name=op.f('fk_movie_person_person_id_person'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint(
            'movie_id', 'person_id', 'role_type', name=op.f('pk_movie_person')
        ),
    )
    op.create_table(
        'user_movie',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('movie_id', sa.Integer(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('WANT', 'WATCHING', 'WATCHED', 'DROPPED', name='watchstatus'),
            nullable=False,
        ),
        sa.Column('rating', sa.SmallInteger(), nullable=True),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('is_favorite', sa.Boolean(), nullable=False),
        sa.Column('rewatch_count', sa.SmallInteger(), nullable=False),
        sa.Column(
            'added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column('watched_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.CheckConstraint(
            'rating >= 1 AND rating <= 10', name=op.f('ck_user_movie_rating_range')
        ),
        sa.ForeignKeyConstraint(
            ['movie_id'],
            ['movie.id'],
            name=op.f('fk_user_movie_movie_id_movie'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['user.id'], name=op.f('fk_user_movie_user_id_user'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user_movie')),
        sa.UniqueConstraint('user_id', 'movie_id', name=op.f('uq_user_movie_user_id')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_movie')
    op.drop_table('movie_person')
    op.drop_table('movie_category')
    op.drop_table('person')
    op.drop_table('movie')
    op.drop_table('category')
    sa.Enum(name='watchstatus').drop(op.get_bind())
    sa.Enum(name='roletype').drop(op.get_bind())
    sa.Enum(name='mediatype').drop(op.get_bind())
    # ### end Alembic commands ###
